package clases;
// Generated 2 feb 2023 17:33:59 by Hibernate Tools 5.4.33.Final

import java.util.Date;

/**
 * AsignaProyecto generated by hbm2java
 */
public class AsignaProyecto implements java.io.Serializable {

	private AsignaProyectoId id;
	private Empleado empleado;
	private Proyecto proyecto;
	private Date fechaFin;

	public AsignaProyecto() {
	}

	public AsignaProyecto(AsignaProyectoId id, Empleado empleado, Proyecto proyecto) {
		this.id = id;
		this.empleado = empleado;
		this.proyecto = proyecto;
	}

	public AsignaProyecto(AsignaProyectoId id, Empleado empleado, Proyecto proyecto, Date fechaFin) {
		this.id = id;
		this.empleado = empleado;
		this.proyecto = proyecto;
		this.fechaFin = fechaFin;
	}

	public AsignaProyectoId getId() {
		return this.id;
	}

	public void setId(AsignaProyectoId id) {
		this.id = id;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

}
