package clases;
// Generated 2 feb 2023 17:33:59 by Hibernate Tools 5.4.33.Final

import java.util.Date;

/**
 * AsignaProyectoId generated by hbm2java
 */
public class AsignaProyectoId implements java.io.Serializable {

	private String dniEmpleado;
	private int idProyecto;
	private Date fechaInicio;

	public AsignaProyectoId() {
	}

	public AsignaProyectoId(String dniEmpleado, int idProyecto, Date fechaInicio) {
		this.dniEmpleado = dniEmpleado;
		this.idProyecto = idProyecto;
		this.fechaInicio = fechaInicio;
	}

	public String getDniEmpleado() {
		return this.dniEmpleado;
	}

	public void setDniEmpleado(String dniEmpleado) {
		this.dniEmpleado = dniEmpleado;
	}

	public int getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(int idProyecto) {
		this.idProyecto = idProyecto;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AsignaProyectoId))
			return false;
		AsignaProyectoId castOther = (AsignaProyectoId) other;

		return ((this.getDniEmpleado() == castOther.getDniEmpleado()) || (this.getDniEmpleado() != null
				&& castOther.getDniEmpleado() != null && this.getDniEmpleado().equals(castOther.getDniEmpleado())))
				&& (this.getIdProyecto() == castOther.getIdProyecto())
				&& ((this.getFechaInicio() == castOther.getFechaInicio())
						|| (this.getFechaInicio() != null && castOther.getFechaInicio() != null
								&& this.getFechaInicio().equals(castOther.getFechaInicio())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDniEmpleado() == null ? 0 : this.getDniEmpleado().hashCode());
		result = 37 * result + this.getIdProyecto();
		result = 37 * result + (getFechaInicio() == null ? 0 : this.getFechaInicio().hashCode());
		return result;
	}

}
