package clases;
// Generated 2 feb 2023 17:33:59 by Hibernate Tools 5.4.33.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto implements java.io.Serializable {

	private int idProyecto;
	private Empleado empleado;
	private String nomProyecto;
	private Date fechaIni;
	private Date fechaFin;
	private Set asignaProyectos = new HashSet(0);

	public Proyecto() {
	}

	public Proyecto(int idProyecto, Empleado empleado, String nomProyecto, Date fechaIni) {
		this.idProyecto = idProyecto;
		this.empleado = empleado;
		this.nomProyecto = nomProyecto;
		this.fechaIni = fechaIni;
	}

	public Proyecto(int idProyecto, Empleado empleado, String nomProyecto, Date fechaIni, Date fechaFin,
			Set asignaProyectos) {
		this.idProyecto = idProyecto;
		this.empleado = empleado;
		this.nomProyecto = nomProyecto;
		this.fechaIni = fechaIni;
		this.fechaFin = fechaFin;
		this.asignaProyectos = asignaProyectos;
	}

	public int getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(int idProyecto) {
		this.idProyecto = idProyecto;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public String getNomProyecto() {
		return this.nomProyecto;
	}

	public void setNomProyecto(String nomProyecto) {
		this.nomProyecto = nomProyecto;
	}

	public Date getFechaIni() {
		return this.fechaIni;
	}

	public void setFechaIni(Date fechaIni) {
		this.fechaIni = fechaIni;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public Set getAsignaProyectos() {
		return this.asignaProyectos;
	}

	public void setAsignaProyectos(Set asignaProyectos) {
		this.asignaProyectos = asignaProyectos;
	}

}
